### ISSUE TITLE
license

### ISSUE THREAD

**Issue by benman1** [asiviero/fuzzy_time_series_predictor#2]
Hi
This looks amazing. Could you release this under an open license such as MIT or similar?

**Comment by asiviero** [comment]
hey @benman1 , apologies for taking so long. I haven't touched this code in so long as my interests have shifted out of it, but I'll add MIT just to avoid any confusion

**Comment by asiviero** [comment]
added in https://github.com/asiviero/fuzzy_time_series_predictor/commit/5e535225cbbe68696d51e7d622a73de7bd20c9d2
